{
    'name': 'Subscription Management',
    'description': 'This module is used to manage subscription Information',
    'author': 'Skyscend Business Solutions Pvt. Ltd.',
    'website': 'https://www.skyscendbs.com',
    'version': '1.0',
    'depends': ['base', 'mail','web'],
    'data': [
        'security/sub_manage_security.xml',
        'security/ir.model.access.csv',
        'data/user_sequence.xml',
        'views/recurrence_period_view.xml',
        'views/types_view.xml',
        'views/subtype_subscription_view.xml',
        'views/addsubscription_view.xml',
        'views/subscription_close.xml',
        'wizard/subscription_close_wizard.xml',
        'report/subscriber_analysis_view.xml',
        'report/reports.xml',
        'views/report_subscriber_template.xml',
        'wizard/subscriber_xlsx_report_view.xml',
        'wizard/subscriber_report_wiz_view.xml',
        'views/res_config_settings_views.xml',
        'wizard/subscription_type_wizard_views.xml',
        'wizard/subscription_wizard_view_9.xml',
        'wizard/add_subscription_wizard_view.xml',
        'views/subscriber_view.xml',
    ],
    'assets': {
        'web.assets_backend': [
            'subscription_managaement/static/src/scss/test_style.scss'
        ],
    },
    'auto_install': False,
    'installable': True,
    'application': True,
}
