{
    'name': 'Subscription Management',
    'author': 'anjana dafda',
    'version': '1.0',
    'category': 'Sales/Subscriptions',
    'sequnce': -100,
    'summary': 'Manage subscription plans and customer subscriptions',
    'website': 'https://www.skyscendbs.com',
    'depends': ['base'],
    'data': [
        'security/subscription_security.xml',
        'security/ir.model.access.csv',
        'views/subscription_view.xml',
        'views/plans_view.xml',
        'views/types_view.xml',
        'views/premium_view.xml',
    ],
    'installable': True,
    'application': True,
    'auto_install': False,
}
